import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* test layout */}
        {/* might need to conditionally render layouts based on url */}
        <div className="flex h-dvh w-screen flex-col">
          <div className="mt-14 flex h-[calc(100vh-56px)] min-h-67.5 w-full flex-col items-center justify-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
